# Generated by Django 3.0.3 on 2020-02-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_room_inadvance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_no',
            new_name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='room',
            name='available_to',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Room')),
            ],
        ),
    ]
