# Generated by Django 3.0.3 on 2020-02-19 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200219_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
