# Generated by Django 3.0.3 on 2020-02-20 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200219_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Manager'),
        ),
    ]
